-- ASCII ART HERE
-- https://www.fancytextpro.com/BigTextGenerator
-- 3 Empty lines between each "section"
-- Function Calling as the last one



------------------------------------------------------------------------------------
-- Section 1
------------------------------------------------------------------------------------




------------------------------------------------------------------------------------
-- Function Calling
------------------------------------------------------------------------------------

local guide = {}

function guide.Start()
    -- call functions from here 
end

return guide